### ISSUE TITLE
This Go Log library will be the best one, I think.

### ISSUE THREAD

**Issue by TIGERB** [appliedgocode/what#5]
This Go Log library will be the best one, I think.

**Comment by christophberger** [comment]
Thank you! <3

Keep in mind that `what` is purely meant for ad-hoc debug logging while developing code. For production logging, minimalists use `log.Print/f/ln`, others will want to choose the log library that works best in their ecosystem (think orchestration frameworks like Kubernetes, different cloud infrastructures, microservice frameworks, structured logging requirements, logging suitable for log collectors, etc)
